name: Sync Branch with Main
on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge changes from main into devm
        run: |
          git fetch origin
          git checkout devm
          git merge --no-commit --no-ff origin/main
          git checkout $(git diff --name-only --diff-filter=U | awk -F/ '{print $1}' | sort -u)
          git commit -m "Merge changes from main into devm"
          git push origin devm
